<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[database is connected]]>
    </line>
    <line>
      <![CDATA[database is disconnected]]>
    </line>
  </reporter-output>
  <suite started-at="2023-01-19T12:22:33 IST" name="Default suite" finished-at="2023-01-19T12:23:02 IST" duration-ms="29647">
    <groups>
    </groups>
    <test started-at="2023-01-19T12:22:33 IST" name="Default test" finished-at="2023-01-19T12:23:02 IST" duration-ms="29647">
      <class name="com.crm.actitime.testscripts.CreateCustomer">
        <test-method is-config="true" signature="databaseconnection()[pri:0, instance:com.crm.actitime.testscripts.CreateCustomer@f736069]" started-at="2023-01-19T12:22:33 IST" name="databaseconnection" finished-at="2023-01-19T12:22:33 IST" duration-ms="9" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[database is connected]]>
            </line>
          </reporter-output>
        </test-method> <!-- databaseconnection -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:com.crm.actitime.testscripts.CreateCustomer@f736069]" started-at="2023-01-19T12:22:33 IST" name="launchBrowser" finished-at="2023-01-19T12:22:54 IST" duration-ms="20749" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="login()[pri:0, instance:com.crm.actitime.testscripts.CreateCustomer@f736069]" started-at="2023-01-19T12:22:54 IST" name="login" finished-at="2023-01-19T12:22:54 IST" duration-ms="319" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="createcustomer()[pri:0, instance:com.crm.actitime.testscripts.CreateCustomer@f736069]" started-at="2023-01-19T12:22:54 IST" name="createcustomer" finished-at="2023-01-19T12:22:54 IST" duration-ms="16" status="FAIL">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
Unhandled exception type IOException
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 
Unhandled exception type IOException

at com.crm.actitime.testscripts.CreateCustomer.createcustomer(CreateCustomer.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createcustomer -->
        <test-method is-config="true" signature="logout()[pri:0, instance:com.crm.actitime.testscripts.CreateCustomer@f736069]" started-at="2023-01-19T12:22:54 IST" name="logout" finished-at="2023-01-19T12:23:02 IST" duration-ms="8043" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.crm.actitime.testscripts.CreateCustomer@f736069]" started-at="2023-01-19T12:23:02 IST" name="closeBrowser" finished-at="2023-01-19T12:23:02 IST" duration-ms="147" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="databasedisconnection()[pri:0, instance:com.crm.actitime.testscripts.CreateCustomer@f736069]" started-at="2023-01-19T12:23:02 IST" name="databasedisconnection" finished-at="2023-01-19T12:23:02 IST" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[database is disconnected]]>
            </line>
          </reporter-output>
        </test-method> <!-- databasedisconnection -->
      </class> <!-- com.crm.actitime.testscripts.CreateCustomer -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
